---
##################################################################################################################
# Mitsubishi ECHONET Climate Component for Home Assistant
# A Home Assistant custom component for use with ECHONET enabled Mitsubishi HVAC systems
# using the MAC-568IF-E WiFi Adaptor.
#
# URL: https://github.com/scottyphillips/mitsubishi_hass
#
# EntityID: climate.man_cave
##################################################################################################################
platform: mitsubishi
name: Man Cave
ip_address: 192.168.20.212
