---
##################################################################################################################
# Light Group
# The group light platform lets you combine multiple lights into one entity.
#
# URL: https://www.home-assistant.io/integrations/light.group/
#
# EntityID: light.living_room_television
##################################################################################################################
platform: group
name: Living Room Television
entities:
  - light.living_room_television_stand
  - light.light_box_one