---
##############################################################################################
# Cover Group
# The group platform can create a cover that combines several cover entities into one.
#
# URL: https://www.home-assistant.io/integrations/cover.group/
#
# EntityID: cover.dining_room_curtains
##############################################################################################
platform: group
name: Dining Room Curtains
entities:
  - cover.dining_room_corner_curtain
  - cover.dining_room_small_window_curtain
