---
##############################################################################################
# MQTT Binary Sensor
# The mqtt binary sensor platform uses an MQTT message received to set the binary sensorâ€™s
# state to on or off.
#
# URL: https://www.home-assistant.io/integrations/binary_sensor.mqtt/
#
# Device: NodeMCU E44EC2 (front-door-multisensor)
# EntityID: binary_sensor.hall_multisensor_motion
##############################################################################################
platform: mqtt
name: Hall MultiSensor Motion
state_topic: E44EC2/sensor/motion
availability_topic: E44EC2/status
device_class: motion
