---
##############################################################################################
# Template Binary Sensor
# The template platform supports binary sensors which get their values from other entities.
# The state of a Template Binary Sensor can only be on or off.
#
# URL: https://www.home-assistant.io/integrations/binary_sensor.template
#calendar.family_school_holiday
# EntityID: binary_sensor.school_today
##############################################################################################
platform: template
sensors:
  school_today:
    friendly_name: School Today
    value_template: >-
      {% set sh_start_date =
        (as_timestamp(state_attr('calendar.family_school_holiday', 'start_time'))) | float | default(0) %}
      {% set sh_end_date =
        (as_timestamp(state_attr('calendar.family_school_holiday', 'end_time'))) | float | default(0) %}
      {% set today_date = as_timestamp(now()) | float | default(0) %}
      {% if ( ( (today_date >= sh_start_date) and
        (today_date <= sh_end_date)) or
        is_state('binary_sensor.workday_today', 'off')) %}
        false
      {% else %}
        true
      {% endif %}
