---
##############################################################################################
# Workday
# The workday binary sensor indicates, whether the current day is a workday or not.
#
# URL: https://www.home-assistant.io/integrations/workday/
#
# EntityID: binary_sensor.workday_tomorrow
##############################################################################################
platform: workday
name: Workday Tomorrow
country: NZ
province: WGN
days_offset: 1
