---
##############################################################################################
# MJPEG IP Camera
# The mjpeg camera platform allows you to integrate IP cameras which are capable to stream
# their video with MJPEG into Home Assistant.
#
# URL: https://www.home-assistant.io/integrations/mjpeg/
#
# EntityID: camera.fdc
##############################################################################################
platform: mjpeg
mjpeg_url: http://192.168.1.215:23456/mjpg/FDC/video.mjpeg
name: FDC
username: !secret bi_username
password: !secret bi_password
authentication: basic
