---
##############################################################################################
# MQTT Sensor
# This mqtt sensor platform uses the MQTT message payload as the sensor value.
#
# URL: https://www.home-assistant.io/integrations/sensor.mqtt/
#
# EntityID: sensor.bedroom_nico_multisensor_luminance
##############################################################################################
platform: mqtt
name: Bedroom Nico MultiSensor Luminance
state_topic: 532B98/sensor/lux
unit_of_measurement: LUX
availability_topic: 532B98/status
