---
##################################################################################################################
# MQTT Switch
# The mqtt switch platform lets you control your MQTT enabled switches.
#
# URL: https://www.home-assistant.io/integrations/switch.mqtt/
#
# Device: D1Mini_14B847 Master - 4 Channel Relay - 01
# EntityID: switch.bedroom_master_electric_blanket_tamara
##################################################################################################################
platform: mqtt
name: Bedroom Master Electric Blanket Tamara
state_topic: stat/D1Mini_14B847/POWER1
command_topic: cmnd/D1Mini_14B847/POWER1
availability_topic: tele/D1Mini_14B847/LWT
qos: 1
payload_on: "ON"
payload_off: "OFF"
payload_available: Online
payload_not_available: Offline
retain: false
