---
##################################################################################################################
# Template Switch
# The template platform creates switches that combines components.
#
# URL: https://www.home-assistant.io/integrations/switch.template/
#
# EntityID: switch.ender_3
##################################################################################################################
platform: template
switches:
  ender_3:
    friendly_name: Ender 3
    value_template: "{{ is_state('binary_sensor.ender_3_octoprint','on') }}"
    turn_on:
      service: switch.turn_on
      entity_id: switch.ender_3_pow
    turn_off:
      service: script.turn_on
      entity_id: script.shutdown_ender_3
