---
##################################################################################################################
# MQTT Switch
# The mqtt switch platform lets you control your MQTT enabled switches.
#
# URL: https://www.home-assistant.io/integrations/switch.mqtt/
# Device: Office Camera
# EntityID: switch.lrc
##################################################################################################################

platform: mqtt
name: LRC
icon: mdi:light-switch
command_topic: BlueIris/admin
payload_on: camera=LRC&enable=1
payload_off: camera=LRC&enable=0
qos: 1
retain: false
