---
id: kitchen_light_off_sun
alias: Kitchen Light Off Sun
description: Turn off kitchen light when sun rise.
trigger:
  platform: sun
  event: sunrise
action:
  - service: light.turn_off
    entity_id:
      - light.kitchen_side
      - light.kitchen_ceiling
      - light.kitchen_cupboard
