---
esphome:
  name: ${node_name}
  comment: ${node_comment}
  platform: ESP8266
  board: esp01_1m
  build_path: ./build/${node_name}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - <<: !include sensor/uptime.config.yaml
  - <<: !include sensor/wifi_signal.config.yaml

output:
  - platform: gpio
    pin: GPIO13
    id: relay01
  - platform: gpio
    pin: GPIO12
    id: relay02
  - platform: gpio
    pin: GPIO14
    id: relay03

binary_sensor:
  # Top
  - platform: gpio
    id: button_top
    pin:
      number: GPIO16
      mode: INPUT
      inverted: true
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
        - logger.log: "Double Clicked"
    - timing:
        - ON for at least 1.1s
        - OFF for at least 0.5s
      then:
        - logger.log: "Single Long Clicked"
    - timing:
        - ON for at most 1s
        - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked"
        - light.toggle: light_top

  # Middle
  - platform: gpio
    id: button_middle
    pin:
      number: GPIO5
      mode: INPUT
      inverted: true
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
        - logger.log: "Double Clicked"
    - timing:
        - ON for at least 1.1s
        - OFF for at least 0.5s
      then:
        - logger.log: "Single Long Clicked"
    - timing:
        - ON for at most 1s
        - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked"
        - light.toggle: light_middle

  # Bottom
  - platform: gpio
    id: button_bottom
    pin:
      number: GPIO4
      mode: INPUT
      inverted: true
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
        - logger.log: "Double Clicked"
    - timing:
        - ON for at least 1.1s
        - OFF for at least 0.5s
      then:
        - logger.log: "Single Long Clicked"
    - timing:
        - ON for at most 1s
        - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked"
        - light.toggle: light_bottom

light:
  - platform: binary
    name: ${device_verbose_name} Top
    output: relay01
    id: light_top
  - platform: binary
    name: ${device_verbose_name} Middle
    output: relay02
    id: light_middle
  - platform: binary
    name: ${device_verbose_name} Bottom
    output: relay03
    id: light_bottom

switch:
  - platform: restart
    name: ${device_verbose_name} Restart
    id: switch_restart

text_sensor:
  - <<: !include text_sensor/version.config.yaml

status_led:
  pin:
    number: GPIO2
    inverted: true
