---
title: CCTV
path: admin-cctv-last-triggered
icon: mdi:cctv
panel: true
cards:
  - type: custom:layout-card
    layout: vertical
    column_width: [350, 525]
    cards:
      - title: Cameras
        type: entities
        show_header_toggle: false
        entities:
          - entity: switch.byc
            name: Backyard
          - entity: switch.dec
            name: Deck
          - entity: switch.drc
            name: Dining Room
          - entity: switch.fdc
            name: Front Door
          - entity: switch.hlc
            name: Hall
          - entity: switch.hsc
            name: House Side
          - entity: switch.lrc
            name: Living Room
          - entity: switch.mcc
            name: Man Cave
          - entity: switch.ofc
            name: Office
      - break
      - aspect_ratio: 0%
        entity: camera.byc_last_trigger
        show_state: false
        type: picture-entity
      - aspect_ratio: 0%
        entity: camera.dec_last_trigger
        show_state: false
        type: picture-entity
      - aspect_ratio: 0%
        entity: camera.drc_last_trigger
        show_state: false
        type: picture-entity
      - break
      - aspect_ratio: 0%
        entity: camera.fdc_last_trigger
        show_state: false
        type: picture-entity
      - aspect_ratio: 0%
        entity: camera.hlc_last_trigger
        show_state: false
        type: picture-entity
      - aspect_ratio: 0%
        entity: camera.hsc_last_trigger
        show_state: false
        type: picture-entity
      - break
      - aspect_ratio: 0%
        entity: camera.lrc_last_trigger
        show_state: false
        type: picture-entity
      - aspect_ratio: 0%
        entity: camera.mcc_last_trigger
        show_state: false
        type: picture-entity
      - aspect_ratio: 0%
        entity: camera.ofc_last_trigger
        show_state: false
        type: picture-entity

