---
title: Dining Room
icon: mdi:silverware-fork-knife
path: dining-room
panel: true
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: vertical-stack
        cards:
          - !include
            - ../templates/heading.yaml
            - title: <ha-icon icon="mdi:silverware-fork-knife"></ha-icon> Dining Room

          - title: Dining Room
            type: picture-glance
            camera_image: camera.drc
            camera_view: live
            entities:
              - binary_sensor.drc_motion

      - type: horizontal-stack
        cards:
          - name: Ceiling
            type: custom:button-card
            hold_action:
              action: more-info
            entity: light.dining_room_ceiling

          - name: Backyard
            type: custom:button-card
            hold_action:
              action: more-info
            entity: light.backyard

      - title: Curtains
        type: entities
        show_header_toggle: false
        entities:
          - entity: cover.dining_room_small_window_curtain
            name: Small Window
          - entity: cover.dining_room_corner_curtain
            name: Corner Window
