---
icon: mdi:docker
panel: true
path: docker
title: Docker
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - title: swart-ninja-smart-home
        show_header_toggle: false
        type: entities
        entities:
          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: homeassistant
              entity_name: Home Assistant
              entity_icon: mdi:home-assistant

          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: mariadb
              entity_name: MariaDB
              entity_icon: mdi:database
              show_network: true

          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: influxdb
              entity_name: InfluxDB
              entity_icon: mdi:database
              show_network: true

          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: mosquitto
              entity_name: Mosquitto
              entity_icon: mdi:forum
              show_network: true

          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: grafana
              entity_name: Grafana
              entity_icon: mdi:chart-bar
              show_network: true

          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: chronograf
              entity_name: Chronograf
              entity_icon: mdi:chart-bar
              show_network: true

          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: deepstack
              entity_name: Deep Stack
              entity_icon: mdi:image-search
              show_network: true

          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: nodered
              entity_name: Node-RED
              entity_icon: mdi:robot-industrial
              show_network: true

          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: esphome
              entity_name: ESPHome
              entity_icon: mdi:chip



      - break

      - title: media
        show_header_toggle: false
        type: entities
        entities:
          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: plexmediaserver
              entity_name: Plex Media Server
              entity_icon: mdi:plex

          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: radarr
              entity_name: Radarr
              entity_icon: mdi:movie-roll
              show_network: true
          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: sonarr
              entity_name: Sonarr
              entity_icon: mdi:television-box
              show_network: true

          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: xteve
              entity_name: Xteve
              entity_icon: mdi:calculator-variant

      - break

      - title: games
        show_header_toggle: false
        type: entities
        entities:
          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: minecraft_server_01
              entity_name: Minecraft Server 01
              entity_icon: mdi:minecraft
              show_network: true

          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: minecraft_server_02
              entity_name: Minecraft Server 02
              entity_icon: mdi:minecraft
              show_network: true

          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: minecraft_server_03
              entity_name: Minecraft Server 03
              entity_icon: mdi:minecraft
              show_network: true

      - break

      - title: tools
        show_header_toggle: false
        type: entities
        entities:
          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: unifi-controller
              entity_name: Unifi Controller
              entity_icon: mdi:router-wireless
              show_network: true
          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: tasmoadmin
              entity_name: TasmoAdmin
              entity_icon: mdi:view-list
              show_network: true
          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: duplicati
              entity_name: Duplicati
              entity_icon: mdi:cloud-upload
              show_network: true
          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: watchtower
              entity_name: Watchtower
              entity_icon: mdi:lighthouse
              show_network: true
          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: apprise
              entity_name: Apprise
              entity_icon: mdi:cellphone-message
              show_network: true
          - !include
            - ../templates/folding_entity/monitor_docker.yaml
            - container_name: portainer
              entity_name: Portainer
              entity_icon: mdi:docker
              show_network: true