---
icon: mdi:highway
panel: true
path: hall
title: Hall
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: vertical-stack
        cards:
          - !include
            - ../templates/heading.yaml
            - title: <ha-icon icon="mdi:highway"></ha-icon> Hall

          - title: Hall
            type: picture-glance
            camera_image: camera.hlc
            camera_view: live
            entities:
              - binary_sensor.lrc_motion
          - title: Front Door
            type: picture-glance
            camera_image: camera.fdc
            camera_view: live
            entities:
              - binary_sensor.fdc_motion

      - break

      - type: vertical-stack
        cards:
          - name: Ceiling
            type: light
            entity: light.hall_zw111_nano_dimmer
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                template: motion_sensor_btn
                entity: binary_sensor.hall_motion
              - type: custom:button-card
                template: door_sensor_btn
                entity: binary_sensor.hall_multisensor_door

      - !include
        - ../templates/esphome_multisensor_graphs_card.yaml
        - node_name: hall_multisensor

      - break

      - !include
        - ../templates/esphome_multisensor_entities_card.yaml
        - node_name: hall_multisensor
          show_led: false
          show_door: true
          show_motion: true

      - title: Doorbell
        type: entities
        show_header_toggle: false
        entities:
          - entity: switch.doorbell_chime
            name: Chime
          - entity: binary_sensor.doorbell
            name: Pressed

      - break

      - title: Hall ZW111 Nano Dimmer
        type: entities
        show_header_toggle: false
        entities:
          - entity: zwave.hall_zw111_nano_dimmer
          - entity: light.hall_zw111_nano_dimmer
            name: Light
          - entity: sensor.hall_zw111_nano_dimmer_current
            name: Current
          - entity: sensor.hall_zw111_nano_dimmer_energy
            name: Energy
          - entity: sensor.hall_zw111_nano_dimmer_power
            name: Power
          - entity: sensor.hall_zw111_nano_dimmer_previous_reading
            name: Previous reading
          - entity: sensor.hall_zw111_nano_dimmer_voltage
            name: Voltage
