---
icon: mdi:fridge
panel: true
path: kitchen
title: Kitchen
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: vertical-stack
        cards:
          - !include
            - ../templates/heading.yaml
            - title: <ha-icon icon="mdi:fridge"></ha-icon> Kitchen

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - entity: light.kitchen_ceiling
                hold_action:
                  action: more-info
                # icon: mdi:ceiling-light
                name: Ceiling
                type: custom:button-card
              - entity: light.kitchen_side
                hold_action:
                  action: more-info
                # icon: mdi:track-light
                name: Side
                type: custom:button-card
              - entity: binary_sensor.kitchen_motion
                template: motion_sensor_btn
                type: custom:button-card

          - entity: light.kitchen_cupboard
            name: Cupboards
            type: light

      - type: custom:mini-media-player
        entity: media_player.kitchen_apple_tv
        icon: mdi:apple
        artwork: cover
        name: Apple TV

      - break

      - type: vertical-stack
        cards:
          - type: custom:mini-graph-card
            font_size: 75
            line_width: 3
            entities:
              - name: Temperature
                color: var(--light-primary-color)
                entity: sensor.kitchen_multisensor_temperature
              - name: Real feel
                color: var(--dark-primary-color)
                entity: sensor.kitchen_multisensor_real_feel
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                font_size: 75
                line_color: var(--complement-color-one)
                line_width: 4
                entities:
                  - entity: sensor.kitchen_multisensor_humidity
                    name: Humidity
              - type: custom:mini-graph-card
                font_size: 75
                line_color: var(--complement-color-two)
                line_width: 4
                entities:
                  - entity: sensor.kitchen_multisensor_luminance
                    name: Luminance

      - break

      - title: MultiSensor
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.kitchen_multisensor
            name: LED
          - entity: binary_sensor.kitchen_multisensor_motion
            name: Motion
          - entity: sensor.kitchen_multisensor_temperature
            name: Temperature
          - entity: sensor.kitchen_multisensor_real_feel
            name: Real feel
          - entity: sensor.kitchen_multisensor_humidity
            name: Humidity
          - entity: sensor.kitchen_multisensor_luminance
            name: LED
          - entity: sensor.kitchen_multisensor_wifi
            name: WiFi

      - title: Motion & Cupboard
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.kitchen_cupboard
            name: Cupboard LED
          - entity: binary_sensor.kitchen_motionsensor_motion
            name: Motion
          - entity: sensor.kitchen_motionsensor_wifi
            name: WiFi
