---
icon: mdi:fridge
panel: true
path: kitchen
title: Kitchen
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: vertical-stack
        cards:
          - !include
            - ../templates/heading.yaml
            - title: <ha-icon icon="mdi:fridge"></ha-icon> Kitchen

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - entity: light.kitchen_ceiling
                hold_action:
                  action: more-info
                # icon: mdi:ceiling-light
                name: Ceiling
                type: custom:button-card
              - entity: light.kitchen_side
                hold_action:
                  action: more-info
                # icon: mdi:track-light
                name: Side
                type: custom:button-card
              - entity: binary_sensor.kitchen_motion
                template: motion_sensor_btn
                type: custom:button-card

          - entity: light.kitchen_cupboard
            name: Cupboards
            type: light

      - type: custom:mini-media-player
        entity: media_player.kitchen_apple_tv
        icon: mdi:apple
        artwork: cover
        name: Apple TV

      - break

      - !include
        - ../templates/esphome_multisensor_graphs_card.yaml
        - node_name: kitchen_multisensor

      - break

      - !include
        - ../templates/esphome_multisensor_entities_card.yaml
        - node_name: kitchen_multisensor
          show_led: true
          show_door: false
          show_motion: true

      - title: Motion & Cupboard
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.kitchen_cupboard
            name: Cupboard LED
          - entity: binary_sensor.kitchen_motionsensor_motion
            name: Motion
          - entity: sensor.kitchen_motionsensor_wifi
            name: WiFi
