---
title: Labs
icon: mdi:test-tube
path: admin-labs
panel: false
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - !include
        - ../templates/heading.yaml
        - title: <ha-icon icon="mdi:test-tube"></ha-icon> Labs

      - !include
        - ../templates/esphome_multisensor_entities.yaml
        - node_name: man_cave_multisensor

      - !include
        - ../templates/esphome_multisensor_graphs.yaml
        - node_name: man_cave_multisensor
          show_led: true
          show_door: false
          show_motion: true

      - type: entities
        title: Entities card
        show_header_toggle: false
        header:
          image: 'https://www.home-assistant.io/images/lovelace/header-footer/balloons-header.png'
          type: picture
        entities:
          - entity: input_text.alexa_actionable_notification
          - switch.nodered_office_motion_lights


 #     {"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}