---
title: Labs
icon: mdi:test-tube
path: admin-labs
panel: true
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - !include
        - ../templates/heading.yaml
        - title: <ha-icon icon="mdi:test-tube"></ha-icon> Labs
