---
title: Living Room
icon: mdi:sofa
panel: true
path: living-room
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: vertical-stack
        cards:
          - !include
            - ../templates/heading.yaml
            - title: <ha-icon icon="mdi:sofa"></ha-icon> Living Room

          - camera_image: camera.lrc
            camera_view: live
            entities:
              - binary_sensor.lrc_motion
            title: Living Room
            type: picture-glance

          - camera_image: camera.dec
            camera_view: live
            entities:
              - binary_sensor.dec_motion
            title: Deck
            type: picture-glance

      - break

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - entity: binary_sensor.living_room_motion
                template: motion_sensor_btn
                type: custom:button-card
              - entity: light.living_room_ceiling
                color: auto
                name: Ceiling
                type: custom:button-card
          - type: horizontal-stack
            cards:
              - name: Mood
                entity: light.living_room_mood
                type: light
              - name: TV
                type: light
                entity: light.living_room_television

      - title: Curtains
        type: entities
        show_header_toggle: false
        entities:
          - entity: cover.living_room_sliding_door_curtain
            name: Sliding Door

      - type: horizontal-stack
        cards:
          - name: Plug One
            type: custom:button-card
            entity: switch.living_room_cupboard_plug_01
          - name: Plug Two
            type: custom:button-card
            entity: switch.living_room_cupboard_plug_02

      - break

      - type: custom:simple-thermostat
        entity: climate.living_room
        step_layout: row
        name: false
        sensors:
          - entity: sensor.living_room_multisensor_temperature
            name: Multi-Sensor
        control:
          hvac:
            auto: false
            fan_only: false
            heat_cool: false
            dry: false

      - !include
        - ../templates/esphome_multisensor_graphs_card.yaml
        - node_name: living_room_multisensor

      - !include
        - ../templates/esphome_multisensor_entities_card.yaml
        - node_name: living_room_multisensor
          show_led: true
          show_door: false
          show_motion: true

      - break

      - type: custom:mod-card
        style: |
          ha-card {
            background: var(--card-background-color);
          }
        card:
          type: vertical-stack
          cards:
            - entity: media_player.living_room_television
              type: media-control
              style: |
                ha-card {
                  border-radius: var(--ha-card-border-radius) var(--ha-card-border-radius) 0 0;
                }
            - entity: media_player.living_room_television
              type: custom:mini-media-player
              hide:
                source: true
                icon: true
                power: true
                controls: true
                name: true
              shortcuts:
                columns: 4
                buttons:
                  - icon: mdi:netflix
                    type: source
                    id: Netflix
                  - icon: mdi:plex
                    type: source
                    id: Plex
                  - icon: mdi:amazon
                    type: source
                    id: Amazon Prime Video
                  - icon: mdi:youtube
                    type: source
                    id: YouTube
              style:
                .: |
                  ha-card {
                    background: var(--card-background-color);
                  }
                .mmp-player > .mmp-player__core:
                  .: |
                    .mmp-player__core > mmp-powerstrip {
                      justify-content: center;
                    }
                mmp-powerstrip:
                  $: |
                    :host > mmp-media-controls {
                      max-width: calc(var(--mmp-unit) * 10);
                    }
            - type: conditional
              conditions:
                - entity: media_player.living_room_television
                  state: "on"
              card:
                type: media-control
                name: Plex
                entity: media_player.living_room_tv_plex

      - type: media-control
        name: Eco Dot
        entity: media_player.living_room_echo_dot