---
title: Max bedroom
icon: mdi:alpha-m-box
panel: true
path: max_bedroom
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: vertical-stack
        cards:
          - !include
            - ../templates/heading.yaml
            - title: <ha-icon icon="mdi:alpha-m-box"></ha-icon> Max bedroom

          - type: horizontal-stack
            cards:
              - entity: light.bedroom_max_ceiling
                name: Ceiling
                type: custom:button-card
              - entity: switch.bedroom_max_electric_blanket
                name: Bed
                type: custom:button-card

          - cards:
              - entity: light.ampersand_multisensor
                name: MultiSensor
                type: entity-button
            type: horizontal-stack

      - break

      - !include
        - ../templates/esphome_multisensor_graphs.yaml
        - node_name: ampersand_multisensor

      - break

      - !include
        - ../templates/esphome_multisensor_entities.yaml
        - node_name: ampersand_multisensor
          show_led: true
          show_door: false
          show_motion: false

      - !include
        - ../templates/esphome_sonoff_pow_entities.yaml
        - node_name: bedroom_max_electric_blanket
          card_title: Electric Blanket

