---
title: Nico bedroom
icon: mdi:alpha-n-box
panel: true
path: nico_bedroom
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - type: vertical-stack
        cards:
          - !include
            - ../templates/heading.yaml
            - title: <ha-icon icon="mdi:alpha-n-box"></ha-icon> Nico bedroom

          - type: horizontal-stack
            cards:
              - entity: light.bedroom_nico_ceiling
                name: Ceiling
                type: custom:button-card
              - entity: switch.bedroom_nico_electric_blanket
                name: Bed
                type: custom:button-card

          - type: horizontal-stack
            cards:
              - entity: light.bedroom_nico_multisensor
                name: MultiSensor
                type: custom:button-card
              - entity: binary_sensor.bedroom_nico_multisensor_motion
                template: motion_sensor_btn
                type: custom:button-card

      - break

      - !include
        - ../templates/esphome_multisensor_graphs_card.yaml
        - node_name: bedroom_nico_multisensor

      - break

      - !include
        - ../templates/esphome_multisensor_entities_card.yaml
        - node_name: bedroom_nico_multisensor
          show_led: true
          show_door: false
          show_motion: true

      - !include
        - ../templates/esphome_sonoff_pow_entities_card.yaml
        - node_name: bedroom_nico_electric_blanket
          card_title: Electric Blanket
