---
title: Office
icon: mdi:desktop-tower-monitor
panel: true
path: office
visible:
  - user: 7d15022a12ef4ca0a18a84419893635d
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - !include
        - ../templates/heading.yaml
        - title: <ha-icon icon="mdi:desktop-tower-monitor"></ha-icon> Office

      - type: custom:state-switch
        entity: user
        states:
          Dick:
            title: Office
            type: picture-glance
            camera_image: camera.ofc
            camera_view: live
            entities:
              - binary_sensor.ofc_motion

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - name: Ceiling
                type: custom:button-card
                entity: light.office_ceiling
                hold_action:
                  action: more-info
              - name: Shelf
                type: custom:button-card
                entity: light.office_shelf
                hold_action:
                  action: more-info

          - type: horizontal-stack
            cards:
              - entity: binary_sensor.office_door_system_door
                name: Door
                template: door_sensor_btn
                type: custom:button-card
              - entity: binary_sensor.office_window_one
                name: Window
                template: window_sensor_btn
                type: custom:button-card
              - entity: binary_sensor.office_window_two
                name: Window
                template: window_sensor_btn
                type: custom:button-card

      - type: vertical-stack
        cards:
          - !include
            - ../templates/sub_heading.yaml
            - title: Door Control
          - type: custom:state-switch
            entity: binary_sensor.office_door_system_door
            default: "on"
            states:
              "on":
                type: horizontal-stack
                cards:
                  - entity: cover.office_door_system_cover
                    icon: mdi:arrow-left-circle
                    lock:
                      duration: 300
                      enabled: >-
                        [[[ return
                        states['binary_sensor.office_door_system_door'].state
                        == "off"; ]]]
                      unlock: hold
                    name: Close
                    show_icon: true
                    show_name: true
                    state:
                      - color: var(--disabled-text-color)
                        operator: template
                        value: |
                          [[[
                            return states['cover.office_door_system_cover'].attributes
                            && (states['cover.office_door_system_cover'].attributes.current_position == 0)
                          ]]]
                    tap_action:
                      action: call-service
                      service: cover.close_cover
                      service_data:
                        entity_id: cover.office_door_system_cover
                    type: custom:button-card
                  - entity: cover.office_door_system_cover
                    icon: mdi:stop-circle
                    name: Stop
                    show_icon: true
                    show_name: true
                    tap_action:
                      action: call-service
                      service: cover.stop_cover
                      service_data:
                        entity_id: cover.office_door_system_cover
                    type: custom:button-card
                  - entity: cover.office_door_system_cover
                    icon: mdi:arrow-right-circle
                    lock:
                      duration: 300
                      enabled: >-
                        [[[ return
                        states['lock.office_door_system_lock'].state
                        == "locked"; ]]]
                      unlock: hold
                    name: Open
                    show_icon: true
                    show_name: true
                    state:
                      - color: var(--disabled-text-color)
                        operator: template
                        value: |
                          [[[
                            return (states['cover.office_door_system_cover'].attributes &&
                            (states['cover.office_door_system_cover'].attributes.current_position == 100)) ||
                            states['lock.office_door_system_lock'].state == "locked"
                          ]]]
                    tap_action:
                      action: call-service
                      service: cover.open_cover
                      service_data:
                        entity_id: cover.office_door_system_cover
                    type: custom:button-card
              "off":
                type: horizontal-stack
                cards:
                  - entity: cover.office_door_system_cover
                    icon: mdi:arrow-left-circle
                    lock:
                      duration: 300
                      enabled: >-
                        [[[ return
                        states['binary_sensor.office_door_system_door'].state
                        == "off"; ]]]
                      unlock: hold
                    name: Close
                    show_icon: true
                    show_name: true
                    state:
                      - color: var(--disabled-text-color)
                        operator: template
                        value: |
                          [[[
                            return states['cover.office_door_system_cover'].attributes
                            && (states['cover.office_door_system_cover'].attributes.current_position == 0)
                          ]]]
                    tap_action:
                      action: call-service
                      service: cover.close_cover
                      service_data:
                        entity_id: cover.office_door_system_cover
                    type: custom:button-card
                  - name: Door Lock
                    color: auto
                    entity: lock.office_door_system_lock
                    hold_action:
                      action: more-info
                    lock:
                      duration: 300
                      enabled: >-
                        [[[ return
                        states['binary_sensor.office_door_system_door'].state
                        == "on"; ]]]
                      unlock: hold
                    state:
                      - color: var(--dark-primary-color)
                        icon: mdi:lock
                        value: locked
                      - color: var(--accent-color)
                        icon: mdi:lock-open
                        value: unlocked
                    tap_action:
                      action: toggle
                    type: custom:button-card
                  - entity: cover.office_door_system_cover
                    icon: mdi:arrow-right-circle
                    lock:
                      duration: 300
                      enabled: >-
                        [[[ return
                        states['lock.office_door_system_lock'].state
                        == "locked"; ]]]
                      unlock: hold
                    name: Open
                    show_icon: true
                    show_name: true
                    state:
                      - color: var(--disabled-text-color)
                        operator: template
                        value: |
                          [[[
                            return (states['cover.office_door_system_cover'].attributes &&
                            (states['cover.office_door_system_cover'].attributes.current_position == 100)) ||
                            states['lock.office_door_system_lock'].state == "locked"
                          ]]]
                    tap_action:
                      action: call-service
                      service: cover.open_cover
                      service_data:
                        entity_id: cover.office_door_system_cover
                    type: custom:button-card

      - break

      - !include
        - ../templates/multisensor_graphs.yaml
        - temp_entity: sensor.office_zw100_multisensor_temperature
          hum_entity: sensor.office_zw100_multisensor_humidity
          lux_entity: sensor.office_zw100_multisensor_luminance

      - break

      - title: Other
        show_header_toggle: false
        type: entities
        entities:
          - entity: switch.nodered_office_lights
            name: Automated Main Light
          - head:
              entity: zwave.office_zw100_multisensor
              name: MultiSensor
            type: custom:fold-entity-row
            entities:
              - entity: zwave.office_zw100_multisensor
                name: ZWave
              - entity: binary_sensor.office_zw100_multisensor_motion
                name: Motion
              - entity: sensor.office_zw100_multisensor_temperature
                name: Temperature
              - entity: sensor.office_zw100_multisensor_humidity
                name: Humidity
              - entity: sensor.office_zw100_multisensor_ultraviolet
                name: Ultraviolet
              - entity: sensor.office_zw100_multisensor_luminance
                name: Luminance
          - head:
              entity: binary_sensor.office_door_system_status
              name: Door System
            type: custom:fold-entity-row
            entities:
              - entity: cover.office_door_system_cover
                name: Cover
              - entity: lock.office_door_system_lock
                name: Lock
              - entity: binary_sensor.office_door_system_door
                name: Door
              - entity: switch.office_door_system_siren
                name: Siren
              - entity: sensor.office_door_system_wifi
                name: WiFi
              - entity: switch.office_door_system_reset
                name: Reset
          - head: media_player.living_room_echo_dot
            items:
              - entity: switch.living_room_echo_dot_do_not_disturb_switch
                name: Do not disturb
              - entity: sensor.living_room_echo_dot_next_alarm
                name: Next alarm
              - entity: sensor.living_room_echo_dot_next_reminder
                name: Next reminder
              - entity: sensor.living_room_echo_dot_next_timer
                name: Next timer
              - entity: switch.living_room_echo_dot_repeat_switch
                name: Repeat
              - entity: switch.living_room_echo_dot_shuffle_switch
                name: Shuffle
            type: custom:fold-entity-row
