---
title: Settings
path: admin-settings
icon: mdi:tune
panel: true
cards:
  - type: custom:layout-card
    layout: vertical
    cards:
      - title: Light Automations
        type: entities
        entities:
          - head:
              entity: group.hall_light_automation
              icon: mdi:highway
              name: Hall
            type: custom:fold-entity-row
            items:
              - entity: automation.hall_light_on_motion
                name: 'On: Motion'
              - entity: automation.hall_light_off_motion
                name: 'Off: Motion'
              - entity: automation.hall_light_on_front_door
                name: 'On: Front Door'
          - head:
              entity: group.bathroom_light_automation
              icon: mdi:shower
              name: Bathroom
            type: custom:fold-entity-row
            items:
              - entity: automation.bathroom_light_on_motion
                name: 'On: Motion'
              - entity: automation.bathroom_light_off_motion
                name: 'Off: Motion'
          - head:
              entity: group.living_room_light_automation
              icon: mdi:sofa
              name: Living Room
            type: custom:fold-entity-row
            items:
              - entity: automation.living_room_light_on_motion
                name: 'On: Motion'
              - entity: automation.living_room_light_off_motion
                name: 'Off: Motion'
          - head:
              entity: group.kitchen_light_automation
              icon: mdi:fridge
              name: Kitchen
            type: custom:fold-entity-row
            items:
              - entity: automation.kitchen_light_on_motion
                name: 'On: Motion'
              - entity: automation.kitchen_light_off_motion
                name: 'Off: Motion'
              - entity: automation.kitchen_light_off_sun
                name: 'Off: Sun'
              - entity: automation.kitchen_cupboard_light_on
                name: 'On: Cupboard'
              - entity: automation.kitchen_cupboard_light_off
                name: 'Off: Cupboard'
              - entity: automation.kitchen_side_light_off
                name: 'Off: Side'
          - entity: input_boolean.dining_room_automated_lights
            icon: mdi:silverware-fork-knife
            name: Dining Room
          - entity: input_boolean.man_cave_kitchen_automated_lights
            icon: mdi:pac-man
            name: Man Cave Kitchen
          - entity: input_boolean.man_cave_automated_lights
            icon: mdi:pac-man
            name: Man Cave


      - title: Curtains Automations
        type: entities
        entities:
          - entity: automation.curtains_close
          - entity: automation.curtains_open

      - title: System Automations
        type: entities
        entities:
          - entity: automation.system_release_notification
            name: Send notification if new release abailable
          - entity: automation.system_shutdown_notification
            name: Send notification on Home Assistant stop
          - entity: automation.system_start_notification
            name: Send notification on Home Assistant start
          - entity: automation.system_start_set_theme
            name: Set theme on Home Assistant start

      - break

      - title: Automation Sensors
        type: entities
        entities:
          - binary_sensor.presence_anyone_home
          - binary_sensor.is_cold
          - binary_sensor.school_today
          - binary_sensor.school_tomorrow
          - binary_sensor.workday_today
          - binary_sensor.workday_tomorrow
          - binary_sensor.dark_outside
          - entity: binary_sensor.updater
            name: Home Assistant Released Version

      - title: System
        type: entities
        show_header_toggle: false
        entities:
          - entity: input_boolean.notifications_text
          - entity: input_boolean.notifications_audio
          - entity: switch.doorbell_chime
            name: Doorbell Chime

      - title: Presence Detection
        type: entities
        entities:
          - entity: input_boolean.presence_location_away_dick
          - entity: input_boolean.presence_location_away_tamara

      - break

      - title: Kids Bed Times
        show_header_toggle: false
        type: entities
        entities:
          - entity: input_datetime.kids_bedtime_school_nights
            name: School nights
          - entity: input_datetime.kids_bedtime_other_nights
            name: Other nights

      - title: Kids Routines
        type: entities
        show_header_toggle: false
        entities:
          - entity: input_boolean.routine_kids_home_school
          - entity: input_boolean.routine_kids_bedtime
          - entity: input_boolean.routine_kids_shower_time

      - title: Alarm
        type: custom:vertical-stack-in-card
        cards:
          - entity: alarm_control_panel.alexa_guard_68602
            states:
              - arm_home
              - arm_away
            type: alarm-panel
          - type: divider
          - entities:
              - entity: input_boolean.house_alarm_silent
              - entity: input_boolean.house_alarm_loud
              - entity: light.alarm_lights_group
            show_header_toggle: false
            type: entities
