wifi:
  fast_connect: true
  networks:
    - ssid: !secret wifi_man_cave_not_ssid
      password: !secret wifi_man_cave_not_password
      bssid: !secret wifi_man_cave_not_bssid
      hidden: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_verbose_name} Hotspot
    password: !secret wifi_ap_password
