---
wifi:
  # use_address: 192.168.30.52
  ssid: !secret wifi_not_ssid
  password: !secret wifi_not_password
  fast_connect: false

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_verbose_name}
    password: !secret wifi_ap_password
