---
icon: mdi:robot
panel: true
path: admin_automation
title: Automation
cards:
  - title: System
    type: entities
    entities:
      - entity: automation.system_release_notification
        name: Send notification if new release abailable
      - entity: automation.system_shutdown_notification
        name: Send notification on Home Assistant stop
      - entity: automation.system_start_notification
        name: Send notification on Home Assistant start
      - entity: automation.system_start_set_theme
        name: Set theme on Home Assistant start

  - title: Lights Automation's
    type: entities
    entities:
      - entity: input_boolean.bathroom_automated_lights
        icon: mdi:shower
        name: Bathroom
      - entity: input_boolean.hall_automated_lights
        icon: mdi:highway
        name: Hall
      - entity: input_boolean.dining_room_automated_lights
        icon: mdi:silverware-fork-knife
        name: Dining Room
      - entity: input_boolean.man_cave_kitchen_automated_lights
        icon: mdi:pac-man
        name: Man Cave Kitchen
      - entity: input_boolean.man_cave_automated_lights
        icon: mdi:pac-man
        name: Man Cave
      - entity: input_boolean.living_room_automated_lights
        icon: mdi:sofa
        name: Living Room
      - entity: input_boolean.kitchen_automated_lights
        icon: mdi:fridge
        name: Kitchen

