---
substitutions:
  node_name: ampersand_multisensor
  node_comment: "Ampersand MultiSensor"
  device_verbose_name: Ampersand MultiSensor

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/nodemcu_base.yaml

sensor:
  - platform: dht
    pin: D1
    temperature:
      name: ${device_verbose_name} Temperature
    humidity:
      name: ${device_verbose_name} Humidity
      icon: mdi:water-percent
    update_interval: 60s
    model: DHT22
  - platform: adc
    pin: A0
    name: ${device_verbose_name} Luminance
    icon: mdi:theme-light-dark
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;

output:
  - platform: esp8266_pwm
    id: output_component1
    pin: D5

light:
  - platform: monochromatic
    name: ${device_verbose_name}
    output: output_component1
