substitutions:
  devicename: ampersand_multisensor
  upper_devicename: Ampersand MultiSensor
  
esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid_hall_not
  password: !secret wifi_password_hall_not
  fast_connect: true
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ampersand Multisensor"
    password: "m4apKZcKrhV9"

captive_portal:

sensor:
  - platform: dht
    pin: D7
    temperature:
      name: ${upper_devicename} Temperature
    humidity:
      name: ${upper_devicename} Humidity
    update_interval: 60s
    model: DHT22
  - platform: adc
    pin: A0
    name: ${upper_devicename} Luminance
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;
  - platform: wifi_signal
    name: ${upper_devicename} WiFi signal
    update_interval: 60s
  - platform: uptime
    name: ${upper_devicename} uptime

light:
  - platform: monochromatic
    name: ${upper_devicename} Light
    output: output_component1

output:
  - platform: esp8266_pwm
    id: output_component1
    pin: D4
    
text_sensor:
  - platform: version
    name: ${upper_devicename} ESPHome version
    
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
