# Device: Sonoff POW EA5999
substitutions:
  node_name: bedroom_max_electric_blanket
  device_verbose_name: Bedroom Max Electric Blanket
  switch_icon: mdi:bed-empty

packages:
  wifi: !include common/wifi/not.hall.yaml
  device_base: !include common/sonoff_pow_r1_base_switch.yaml
