# Device: Sonoff POW 374EE6
substitutions:
  node_name: ender_3
  device_verbose_name: Ender 3
  switch_icon: mdi:printer-3d

packages:
  wifi: !include common/wifi.man_cave.yaml
  device_base: !include common/sonoff_pow_r1_base_switch.yaml
