substitutions:
  node_name: frontdoor_ceiling
  device_verbose_name: Front Door Ceiling

packages:
  wifi: !include common/wifi/not.hall.yaml
  device_base: !include common/shelly_1_base.yaml

# packages:
#   wifi: !include common/wifi/main.yaml
#   device_base: !include common/shelly_1_base_blank.yaml