substitutions:
  node_name: hall_multisensor
  node_comment: "MultiSensor (ID: E44EC2)"
  device_verbose_name: Hall MultiSensor

packages:
  wifi: !include common/wifi/not.hall.yaml
  device_base: !include common/nodemcu_base.yaml

switch:
  - platform: gpio
    pin: D1
    name: ${device_verbose_name} Siren

sensor:
  - platform: dht
    pin: D6
    temperature:
      name: ${device_verbose_name} Temperature
    humidity:
      name: ${device_verbose_name} Humidity
      icon: mdi:water-percent
    update_interval: 60s
    model: DHT22
  - platform: adc
    pin: A0
    name: ${device_verbose_name} Luminance
    icon: mdi:theme-light-dark
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;

binary_sensor:
  - platform: gpio
    pin: D5
    name: ${device_verbose_name} Motion
    device_class: motion
  - platform: gpio
    name: ${device_verbose_name} Door
    device_class: door
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: False

