---
substitutions:
  node_name: kitchen_ceiling
  node_comment: Sonoff Basic 6B1A4E
  device_verbose_name: Kitchen Ceiling
  switch_icon: mdi:track-light

packages:
  wifi: !include common/wifi/not.upstairs.yaml
  device_base: !include common/sonoff_basic_base_switch.yaml
