---
substitutions:
  node_name: kitchen_ceiling
  node_comment: Sonoff Basic 6B1A4E
  device_verbose_name: Kitchen Ceiling

packages:
  wifi: !include common/wifi/not.yaml
  device_base: !include common/sonoff_basic_base_light.yaml
