---
substitutions:
  node_name: living_room_tv_backlight
  node_comment: "ID: 53474A"
  device_verbose_name: Living Room TV Backlight

packages:
  wifi: !include common/wifi/not.hall.yaml
  device_base: !include common/nodemcu_base.yaml

light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: D5
    num_leds: 76
    rgb_order: BRG
    name: ${device_verbose_name}
    effects:
      - random:
      - strobe:
