---
substitutions:
  node_name: sonoff_basic_671faa
  node_comment: Sonoff Basic 671FAA
  device_verbose_name: Sonoff Basic 671FAA
  switch_icon: mdi:light-switch

packages:
  wifi: !include common/wifi/main.yaml
  device_base: !include common/sonoff_basic_base_switch.yaml
