# Device: Sonoff POW 374EAA
substitutions:
  node_name: work_station
  device_verbose_name: Work Station
  switch_icon: mdi:soldering-iron

packages:
  wifi: !include common/wifi/not.man_cave.yaml
  device_base: !include common/sonoff_pow_r1_base_switch.yaml
