---
alias: Shutdown Ender 3
sequence:
  - condition: and
    conditions:
      - condition: state
        entity_id: switch.ender_3
        state: "on"
      - condition: state
        entity_id: binary_sensor.octoprint_printing
        state: "off"
  - service: rest_command.shutdown_octoprint
    data:
      ip: 192.168.1.210
  - wait_template: "{{ is_state('binary_sensor.ender_3_octoprint', 'off') }}"
    timeout: 00:05:00
    continue_on_timeout: false
  - delay: 00:00:05
  - service: switch.turn_off
    entity_id: switch.ender_3
