---
##################################################################################################################
# Home Assistant Cloud
# The Home Assistant Cloud allows you to quickly integrate your local Home Assistant with various cloud services
# like Amazon Alexa and Google Assistant.
#
# URL: https://www.home-assistant.io/integrations/http/
##################################################################################################################
cloud:
  # Customize the Amazon Alexa integration with the Nabu Casa Cloud
  alexa:
    # Optional entity specific configuration for Alexa.
    # These are loaded from a separate directory.
    # entity_config: !include_dir_merge_named ../assistants/alexa
    entity_config: !include_dir_merge_named ../customizations/alexa

    # Filters for entities to include/exclude from Alexa.
    filter:
      include_entities: !include_dir_merge_list ../alexa
