---
##################################################################################################################
# HomeKit
# The HomeKit Bridge integration allows you to forward entities from Home Assistant to Apple HomeKit,
# so they can be controlled from Appleâ€™s Home app and Siri
#
# URL: https://www.home-assistant.io/integrations/homekit
##################################################################################################################
homekit:
  # Need to be individual for each instance of Home Assistant using the integration on the same local network.
  # Between 3 and 25 characters. Alphanumeric and spaces allowed. Default value: Home Assistant Bridge
  name: Home Assistant

  # Configuration for specific entities. All subordinate keys are the corresponding entity
  # ids to the domains, e.g., alarm_control_panel.alarm.
  entity_config: !include_dir_named ../assistants/siri

  # Filters for entities to be included/excluded from HomeKit.
  filter:
    include_entities:
      - climate.living_room
      - climate.man_cave
      - fan.bathroom
