---
##################################################################################################################
# Input Datetime
# The input_datetime integration allows the user to define date and time values that can be controlled
# via the frontend and can be used within automations and templates.
#
# The preferred way to configure input datetime is via the user interface at Configuration -> Helpers.
# Click the add button and then choose the “Date and/or time” option.
#
# URL: https://www.home-assistant.io/integrations/input_datetime/
##################################################################################################################
input_datetime: ~
