---
##############################################################################################
# InfluxDB include entities
# Configure which integrations should be included in recordings to InfluxDB.
# If set, all other entities will not be recorded to InfluxDB. Values set by the exclude
# lists will take precedence.
#
# URL: https://www.home-assistant.io/integrations/influxdb/#include
##############################################################################################
- binary_sensor.kitchen_multisensor_motion
- binary_sensor.kitchen_motion_led_motion
- binary_sensor.kitchen_motion
- sensor.kitchen_motion_led_wifi_signal
- sensor.kitchen_multisensor_wifi_signal
- sensor.kitchen_multisensor_humidity
- sensor.kitchen_multisensor_luminance
- sensor.kitchen_multisensor_temperature
