---
id: bathroom_light_on_motion
alias: Bathroom Light On Motion
description: Turn on bathroom light when there is movement
trigger:
  platform: state
  entity_id: binary_sensor.bathroom_multisensor_motion
  to: 'on'
condition:
  - condition: numeric_state
    entity_id: sensor.bathroom_multisensor_luminance
    below: 60
  - condition: state
    entity_id: light.bathroom_zw111_nano_dimmer
    state: 'off'
action:
  - choose:
      # IF between midnight and 6am Dimmed
      - conditions:
          - condition: time
            before: '06:01:00'
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.bathroom_zw111_nano_dimmer
              brightness: 18
    # ELSE full brightness
    default:
      - service: light.turn_on
        data:
          entity_id: light.bathroom_zw111_nano_dimmer
          brightness: 255
